services:
  ahms-mysql-db:
    container_name: ahms-mysql-db
    image: mysql:8.0.32
    ports:
      - '${AHMS_MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${AHMS_MYSQL_PASSWORD}
      MYSQL_DATABASE: ahms-db
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -u root -p${AHMS_MYSQL_PASSWORD}"
    networks:
      - ahms-network

  ahms-phpmyadmin:
    container_name: ahms-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${AHMS_PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: ahms-mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${AHMS_MYSQL_PASSWORD}
    depends_on:
      - ahms-mysql-db
    networks:
      - ahms-network

  ahms-mailhog:
    container_name: ahms-mailhog
    image: mailhog/mailhog:latest
    ports:
      - '${AHMS_MAILHOG_SERVER_PORT}:1025'
      - '${AHMS_MAILHOG_UI_PORT}:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
    volumes:
      - ./.volumes/mail/mailhog-volume:/home/mailhog
      - ./.volumes/mail/mailhog.conf:/etc/supervisor/conf.d
      - ./.volumes/mail/mailhog-auth.txt:/etc/mailhog-auth.txt
    healthcheck:
      test: [ "CMD", "echo | telnet 127.0.0.1 8025" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
    networks:
      - ahms-network

  ahms-app:
    container_name: ahms-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${AHMS_APP_PORT}:8080
    environment:
      AHMS_DB_HOST: ahms-mysql-db
      AHMS_DB_PORT: 3306
      AHMS_DB_USERNAME: root
      AHMS_DB_PASSWORD: ${AHMS_MYSQL_PASSWORD}
      AHMS_DB_NAME: ahms-db
      AHMS_SERVER_XMS: 1024m
      AHMS_SERVER_XMX: 1024m
      AHMS_JWT_SECRET: ${AHMS_APP_JWT_SECRET}
      AHMS_MAIL_PROTOCOL: smtp
      AHMS_MAIL_HOST: ahms-mailhog
      AHMS_MAIL_PORT: 1025
      AHMS_MAIL_USERNAME: admin
      AHMS_MAIL_PASSWORD: admin
      AHMS_MAIL_SEND_ADDRESS: noreply@ahms.docker.miloszgilga.pl
      AHMS_MAIL_REPLY_ADDRESS: info@ahms.docker.miloszgilga.pl
      AHMS_MAIL_AUTH_ENABLED: false
      AHMS_MAIL_SSL_ENABLED: false
    depends_on:
      - ahms-mysql-db
      - ahms-mailhog
    networks:
      - ahms-network

networks:
  ahms-network:
    driver: bridge
