server:
  port: 8534

spring:
  devtools:
    livereload:
      port: 35731
    restart:
      log-condition-evaluation-delta: false
  liquibase:
    contexts: lq_dev
  datasource:
    url: jdbc:mysql://localhost:8530/ahms-db
    username: root
    password: admin
  jpa:
    show-sql: true
  mail:
    port: 8532
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

application:
  app-name: AirHubMaster DEV
  jwt:
    issuer: airhubmaster-dev
