spring:
  datasource:
    url: jdbc:mysql://${AHMS_DB_HOST}:${AHMS_DB_PORT:3306}/${AHMS_DB_NAME}
    username: ${AHMS_DB_USERNAME}
    password: ${AHMS_DB_PASSWORD}
  liquibase:
    contexts: lq_prod
  mail:
    protocol: ${AHMS_MAIL_PROTOCOL:smtp}
    port: ${AHMS_MAIL_PORT:587}
    username: ${AHMS_MAIL_USERNAME}
    password: ${AHMS_MAIL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
